apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pervol-vi
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
