apiVersion: v1
kind: Pod
metadata:
  name: gpu-2-hk
spec:
  containers:
  - name: gpu-container
    image: hkashyap/evolverl
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 2
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
